spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/quiz
        username: root
        password:
    jpa:
        show-sql: true
        # hibernate:
            #ddl-auto: none
    jackson:
        serialization:
            INDENT_OUTPUT: true

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
