CREATE DATABASE IF NOT EXISTS quiz ;

CREATE TABLE questions (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  question VARCHAR(255) NOT NULL,
  choices JSON NOT NULL,
  answer CHAR(1) NOT NULL
)

CREATE TABLE responses (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  full_name VARCHAR(255) NOT NULL,
  time time(2) NOT NULL
)

DROP TABLE responses;

RENAME TABLE responses TO responses;
